var path = require('path');
var webpack = require('webpack');


module.exports = {
    context: path.resolve('js'),
    entry: ['./about_page', './contact_page','./index/index_page' ],
    output: {
        path: path.resolve('build'),
        publicPath: '/public/assets/',
        filename: "build.js"
    },
    plugins: [
        new webpack.BannerPlugin("+++++++++++++++++++\nGenerated by Webpack version 2.2.1\n++++++++++++++++++\n"),
        new webpack.optimize.UglifyJsPlugin({ 
            include: /build.js/,
            minimize: true
        })
    ],
    devServer: {
        contentBase:  'public'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                enforce: "pre",
                loader: "jshint-loader"
            },
            {
                test: /\.es6/,
                exclude: /node_modules/,
                loader: "babel-loader"
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.(png|jpg)$/,
                exclude: /node_modules/,
                loader: "url-loader?limit=10000"
            },
            {
                test: /\.json$/,
                exclude: /node_modules/,
                loader: "json-loader!" + path.resolve('loaders/strip')
            }
        ]
    },
    resolve: {
        extensions: ['.js', '.es6']
    }
}